# Generated by Django 3.1 on 2021-12-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_youtubevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='image',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='link',
            field=models.CharField(default='cu8khSTiwp0', max_length=200),
            preserve_default=False,
        ),
    ]
