# Generated by Django 3.1 on 2022-01-14 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_facebooklink_twitterlink_youtubelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebooklink',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitterlink',
            name='link',
            field=models.CharField(default='youtube.com', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='youtubelink',
            name='link',
            field=models.CharField(max_length=500),
        ),
    ]
