# Generated by Django 3.1 on 2022-01-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_youtubelink_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
